spring:
  datasource:
    url: jdbc:mysql://localhost/krish_app_microservices
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

